### ISSUE TITLE
module concept

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/violet#41]
Module will have a access chain like `A.B.C`, the syntax are in #31, here introduces another syntax `import <chain>` to introduce context from another module.

All modules not defined by us will get an import statement: `import Core`. Of course, except the `Core` modules we defined.

This issue also requires us to introduce machinery for installed modules finding.

- [x] parse syntax `import Xxx` --- #76 
- [x] external module finding
- [x] extend context with import statements for checking

**Comment by rayshih** [comment]
So after some playing, I think we might need to come up with a build system. To elaborate, considering the following naive recursive implementation:

For typechecking a module:
1. after parsing the source code and forming the surface level AST, we can have a list of import statements of the target module.
2. find the module being imported, apply the typechecking process recursively and get the new env/cxt, and then bring them to the env/cxt to the current module.

And the problem is: if there are 2 modules depend on a same base module, then this naive solution will cause the base module be compiled twice.

Alternatively, if we figure out all the imports for all modules and form a graph, then we can at least do a topological sort, and typecheck through them and accumulate the env/ctx through the process.

If we choose wisely, this can potentially save loads of performance problem of IDE and CI/CD etc. Ideally, we only need to recompile the modules actually changed.

For now, I'd suggest to only do the topo-sort but make sure the compilation process is deterministic, which will be very helpful when we later want to evolve it to proper build system.

**Comment by dannypsnl** [comment]
I guess we leave final is default lookup path configuration?

@rayshih 
1. May you update the checkpoints list above?
2. You might also want to update README too
